site_name: Estrategia de Apertura de Datos
site_url: https://datosgcba.github.io/guia-datos/
site_description: Recursos para la apertura de datos públicos del Gobierno de la Ciudad Autónoma de Buenos Aires.
site_author: Buenos Aires Data
repo_url: https://github.com/datosgcba/

nav:
  - Inicio: index.md
  - Guía para la publicación de datos en formatos abiertos: guia-abiertos.md
  - Guía para la identificación y uso de entidades interoperables: guia-interoperables.md
  - Guía para el uso y la publicación de metadatos: guia-metadatos.md
  - Política de Datos Abiertos: politica-datos-abiertos.md 
  - Glosario: glosario.md

theme:
  name: 'datosgobar_docs'
  custom_dir: 'theme'
  logo: 'assets/images/logos/ba_logo.png'

extra_css:
  - 'assets/stylesheets/extra.css'
  - 'assets/stylesheets/bootstrap.css'
  - 'assets/stylesheets/bastrap.css'
  - 'assets/stylesheets/footer.css'
  - 'assets/stylesheets/header.css'

google_analytics: ['UA-129525617-1', "https://datosgcba.github.io/guia-datos/"]